[package]
name = "highflowey/priority"
version = "0.5.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
description = "Priority based state machines with features to help you change humanoid properties with ease."

[dependencies]
Signal = "sleitnick/signal@2.0.1"
